#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# Define the main branch name
MAIN_BRANCH="main"

# Get the current branch name
current_branch=$(git symbolic-ref --short HEAD)

# Run linting on all branches
echo "Running linting..."
npm run lint ## test.js
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix errors before pushing."
  exit 1
fi

# Run SonarQube only when pushing to the main branch and if sonar is runing
if [ "$current_branch" = "$MAIN_BRANCH" ]; then
 if nc -z localhost 9000; then
   echo "Running SonarQube analysis for main branch..."
   npm run sonar
   if [ $? -ne 0 ]; then
     echo "SonarQube analysis failed - skipping"
     exit 0
   fi
 else
   echo "SonarQube not running - skipping analysis"
 fi
else
 echo "Skipping SonarQube analysis for branch $current_branch."
fi

# Allow the push to proceed
echo "Push succeeded."
exit 0